### ISSUE TITLE
opensllErrorStack

### ISSUE THREAD

**Issue by milesueee** [joshzcold/Cold-Family-Feud#56]
Help, I can't get past this error

`Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (C:\VSCode\family-feud\node_modules\next\dist\compiled\webpack\bundle5.js:133790:18)
    at BulkUpdateDecorator.update (C:\VSCode\family-feud\node_modules\next\dist\compiled\webpack\bundle5.js:133692:50)
    at C:\VSCode\family-feud\node_modules\next\dist\compiled\webpack\bundle5.js:56905:9
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:442:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}`

**Comment by milesueee** [comment]
for everyone having the same problem, copy this code into the terminal before you initiate `npm run start_windows`

`$env:NODE_OPTIONS="--openssl-legacy-provider"`
